### ISSUE TITLE
composer.json hiányzó adatok

### ISSUE THREAD

**Issue by schalkt** [gyuszka3/probamunka#1]
Szia!
Apró észrevételek :)

- futtasd a ```composer diagnose```-t és javítsd a WARNING-okat
- a hiányzó adatokat írd be: name, version, license
- a require részbe írd bele, hogy milyen php verzió szükséges a futtatáshoz, 5.6 vagy 7.x?

**Comment by gyuszka3** [comment]
Üdv
Köszönöm javítva :)
