### ISSUE TITLE
.gitignore és vendor mappa

### ISSUE THREAD

**Issue by schalkt** [gyuszka3/probamunka#2]
Szia!

a /vendor mappát is beküldted a repoba, amit szinte soha nem szoktunk, mert azt mindenki a saját gépén telepíti fel a ```composer install``` használatával

- a /vendor mappát mozgasd át valami ideiglenes helyre, hogy a git úgy vegye az törölve lett
- küld be a repoba a törlést
- hozzd létre a ".gitignore" fájlt és írd bele az első sorba, hogy /vendor
- mozgasd vissza a /vendor mappát

**Comment by gyuszka3** [comment]
Üdv
Köszönöm javítva 😄
