### ISSUE TITLE
PHP Coding Style

### ISSUE THREAD

**Issue by schalkt** [gyuszka3/probamunka#3]
Látom Sublime-t használsz, azt nem ismerem annyira, de érdemes valamilyen coding style-t követni és azt ha lehet beállítani az automatikus formázásnál, ha van ilyen a Sublime-ban.

Amit ajánlok, az a PSR-2 : https://www.php-fig.org/psr/psr-2/

Hogy le tudd tesztelni a kódod az alábbiakat javaslom:
- PHP_CodeSniffer  telepítése: ```composer require "squizlabs/php_codesniffer=*"```
- futtatása: ```.\vendor\bin\phpcs --standard=PSR2 --ignore=\vendor\* [projekt mappa útvonala]```

Ez ki fogja írni php fájlonként, hogy milyen "hibákat" talált.
A .\vendor\bin\phpcfb -t futtatva pedig a nagy részét ki is lehet javítani.
Itt van leírás róla: https://github.com/squizlabs/PHP_CodeSniffer/wiki

**Comment by gyuszka3** [comment]
Üdv
Köszönöm javítva 😄
